liip_imagine:
   #valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filters_sets:
      carre: #nom du filtre
        quality: 75 # qualit√© de l'image
        filters:
          thumbnail:
            size: [200, 200]
            mode: outbound